// Generated by https://quicktype.io
export interface API_RecipeCollection_Response {
    data: Data;
}
interface Data {
    recipeCollection: RecipeCollection;
}

interface RecipeCollection {
    items: Item[];
}

interface Item {
    title: string;
    calories: number;
    photo: Photo;
    description: string;
    chef: Chef | null;
}

interface Chef {
    name: string;
}

interface Photo {
    url: string;
    description: null;
    title: string;
}
